// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_testing_demo/test/integration/auth_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_testing_demo/models/auth_user.dart' as _i3;
import 'package:flutter_testing_demo/services/auth_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthUser_1 extends _i1.SmartFake implements _i3.AuthUser {
  _FakeAuthUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#prefs),
        ),
      ) as _i2.SharedPreferences);

  @override
  bool validateEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #validateEmail,
          [email],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool validatePassword(String? password) => (super.noSuchMethod(
        Invocation.method(
          #validatePassword,
          [password],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool validateDisplayName(String? displayName) => (super.noSuchMethod(
        Invocation.method(
          #validateDisplayName,
          [displayName],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i3.AuthUser> register({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #displayName: displayName,
          },
        ),
        returnValue: _i5.Future<_i3.AuthUser>.value(_FakeAuthUser_1(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #displayName: displayName,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthUser>);

  @override
  _i5.Future<_i3.AuthUser> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<_i3.AuthUser>.value(_FakeAuthUser_1(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.AuthUser>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.AuthUser?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i3.AuthUser?>.value(),
      ) as _i5.Future<_i3.AuthUser?>);

  @override
  _i5.Future<bool> isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> clearAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #clearAllUsers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AuthUser>> getAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #getAllUsers,
          [],
        ),
        returnValue: _i5.Future<List<_i3.AuthUser>>.value(<_i3.AuthUser>[]),
      ) as _i5.Future<List<_i3.AuthUser>>);

  @override
  _i5.Future<_i3.AuthUser> updateUser(_i3.AuthUser? updatedUser) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [updatedUser],
        ),
        returnValue: _i5.Future<_i3.AuthUser>.value(_FakeAuthUser_1(
          this,
          Invocation.method(
            #updateUser,
            [updatedUser],
          ),
        )),
      ) as _i5.Future<_i3.AuthUser>);
}
